name: counter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  get: ^4.0.0
  intl: ^0.18.1
  dartz: ^0.10.1
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GmarketSansB
      fonts:
        - asset: assets/fonts/GmarketSansB.otf
    - family: GmarketSansL
      fonts:
        - asset: assets/fonts/GmarketSansL.otf
    - family: GmarketSansM
      fonts:
        - asset: assets/fonts/GmarketSansM.otf
